name: Pyodide Tests

on:
  workflow_dispatch:
  push: {tags-ignore: ['**'], branches: ['**']}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Conan
        uses: ./.github/workflows/setup-conan
        with:
          python-version: '3.12'
          cache-key: build-pyodide

      - name: Build Wheels
        uses: pypa/cibuildwheel@352e01339f0a173aa2a3eb57f01492e341e83865
        with:
          output-dir: dist

        env:
          CIBW_PLATFORM: pyodide
          CIBW_ENVIRONMENT: 'PY_BUILD_CMAKE_VERBOSE=1 _PY_BUILD_CMAKE_PYODIDE_NO_TOOLCHAIN_FILE=1'

      - name: Upload Wheel package
        uses: actions/upload-artifact@v4
        with:
          name: pyodide-wheels
          path: dist/*.whl
          retention-days: 1

      - run: conan cache clean
